In [ ]:
import pandas as pd
import re
import unicodedata
from data_loader import load_test_data

test_source1, test_source2, test_source3 = load_test_data(
    "../../../dataset"
)

TypeError: load_test_data() takes 0 positional arguments but 1 was given

In [10]:
test_source1 = pd.read_csv(
    "/Users/aaravraj/Downloads/student_resource/dataset/test/test_source1.tsv",
    sep="\t"
)

test_source2 = pd.read_csv(
    "/Users/aaravraj/Downloads/student_resource/dataset/test/test_source2.tsv",
    sep="\t"
)

test_source3 = pd.read_csv(
    "/Users/aaravraj/Downloads/student_resource/dataset/test/test_source3.tsv",
    sep="\t"
)

In [12]:
def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()

    text = unicodedata.normalize("NFKD", text)

    text = "".join(
        c for c in text
        if not unicodedata.combining(c)
    )

    text = text.replace("&", " and ")

    text = re.sub(r"[^a-z0-9\s]", " ", text)

    text = re.sub(r"\s+", " ", text).strip()

    return text

In [14]:
def clean_business_name(text):
    return normalize_text(text)

In [16]:
def clean_address(text):

    if pd.isna(text):
        return ""

    text = str(text).lower().strip()

    text = unicodedata.normalize("NFKD", text)

    text = "".join(
        c for c in text
        if not unicodedata.combining(c)
    )

    text = text.replace("&", " and ")

    replacements = {
        r"\brd\.?\b": "road",
        r"\bst\.?\b": "street",
        r"\bave\.?\b": "avenue",
        r"\bav\.?\b": "avenue",
        r"\bblvd\.?\b": "boulevard",
        r"\bln\.?\b": "lane",
        r"\bdr\.?\b": "drive",
        r"\bhwy\.?\b": "highway"
    }

    for pattern, replacement in replacements.items():
        text = re.sub(pattern, replacement, text)

    text = re.sub(r"[^a-z0-9\s]", " ", text)

    text = re.sub(r"\s+", " ", text).strip()

    return text

In [18]:
def clean_country(text):

    if pd.isna(text):
        return ""

    text = str(text).lower().strip()

    text = re.sub(r"\s+", " ", text)

    return text

In [20]:
for df in [test_source1, test_source2, test_source3]:

    df["business_name_clean"] = (
        df["business_name"]
        .apply(clean_business_name)
    )

    df["business_address_clean"] = (
        df["business_address"]
        .apply(clean_address)
    )

    df["country_clean"] = (
        df["country"]
        .apply(clean_country)
    )

In [22]:
test_source1.head()

,entity_id,business_name,business_address,country,business_name_clean,business_address_clean,country_clean
0,S1-714132312,Zephay Labs Inc,"2621 Cotten Road, Tyler, TX",US,zephay labs inc,2621 cotten road tyler tx,us
1,S1-106407869,Vision Partners Corp,"IA, Iowa City, 1064 Newton Rd, Unit 11",US,vision partners corp,ia iowa city 1064 newton road unit 11,us
2,S1-156285671,<< Team Ecole,"175 Boulevard du Président Franklin Roosevelt,...",France,team ecole,175 boulevard du president franklin roosevelt ...,france
3,S1-689823050,Red Perfect Trading,"Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...",India,red perfect trading,mirzapur ews 12 uttar pradesh mirzapursadar aw...,india
4,S1-921369899,ZNB Club SARL,"Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...",France,znb club sarl,nouvelle aquitaine la teste de buch 5 bis rue ...,france

In [24]:
test_source2.head()

,entity_id,business_name,business_address,country,business_name_clean,business_address_clean,country_clean
0,S2-192345572,Brahma Infosoft,"COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...",India,brahma infosoft,coimatore colony hunsur tqmysore dist karnataka,india
1,S2-566025912,Marina Ecole France Sarl,"63 R. DE DIEPPE, LILLE, Hauts-de-France",France,marina ecole france sarl,63 r de dieppe lille hauts de france,france
2,S2-158121477,SCI Ptit Àmicale,"18 RUE JEN ZAY, Dunkerque, Nord",France,sci ptit amicale,18 rue jen zay dunkerque nord,france
3,S2-89663826,Apex Summit,"67 KENTUCKY ST, SALYERSVILLE, KY",US,apex summit,67 kentucky street salyersville ky,us
4,S2-884102769,Fresh Truist,"8264 FILLY COURT, ROANOKE COUNTY, VA",US,fresh truist,8264 filly court roanoke county va,us

In [26]:
test_source3.head()

,entity_id,business_name,business_address,country,business_name_clean,business_address_clean,country_clean
0,S3-462677478,मॉडर्न फाइनेंस,"No 10 Enkay Square, 448A, Udyog Vihar Phase V,...",India,,no 10 enkay square 448a udyog vihar phase v gu...,india
1,S3-374810425,Shri Sai Infratech Co,"3/115, East Delhi, DL",India,shri sai infratech co,3 115 east delhi dl,india
2,S3-198586129,Fractales Amis Groupe S.A.S,"23 Rue Icmre, La Teste-de-buch, Gironde",France,fractales amis groupe s a s,23 rue icmre la teste de buch gironde,france
3,S3-10300249,Shri Supreme Consulting Private (Limited),"H.no 910 A 3503, Mumbai, महाराष्ट्र",India,shri supreme consulting private limited,h no 910 a 3503 mumbai,india
4,S3-604980231,Prime Realty Ventures Public Limited,"G.t. Karnal Road, Industrial Area, New Delhi, ...",India,prime realty ventures public limited,g t karnal road industrial area new delhi null...,india

In [ ]:
print("Test Source 1")
print(test_source1.isnull().sum())

print("\nTest Source 2")
print(test_source2.isnull().sum())

print("\nTest Source 3")
print(test_source3.isnull().sum())

Test Source 1
entity_id                 0
business_name             0
business_address          0
country                   0
business_name_clean       0
business_address_clean    0
country_clean             0
dtype: int64

Test Source 2
entity_id                      0
business_name                 46
business_address          129408
country                        0
business_name_clean            0
business_address_clean         0
country_clean                  0
dtype: int64

Test Source 3
entity_id                      0
business_name                 59
business_address          136098
country                        0
business_name_clean            0
business_address_clean         0
country_clean                  0
dtype: int64